### ISSUE TITLE
Updated from pytshares and just cant get delegate-feed to work

### ISSUE THREAD

**Issue by iPerky** [xeroc/bitshares-pytools#3]
Here is my process to install and run

```
#https://github.com/xeroc/bitshares-pytools
#as root
pacman -S python-statsmodels python-pip python-requests python-numpy python-prettytable

#as user
git clone https://github.com/xeroc/bitshares-pytools
cd bitshares-pytools
git submodule init
git submodule update
#python-bitsharesrpc
cd python-bitsharesrpc
python setup.py install --user
cd ..
#python-bitsharestools
cd python-bitsharestools
python setup.py install --user
cd ..
#for feeds setup 
cp delegate-feed/config-example.py delegate-feed/config.py
#edit config.py 
nano delegate-feed/config.py # url user passwd unlock wallet delegate_list

#start bitshares (config.json) with httpd_endpoint port from delegate-feed/config.py

#run
delegate-feed/./main.py All
```

but I am getting the following error

```
$ delegate-feed/./main.py All
Loading data: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jason/.local/lib/python3.4/site-packages/bitsharesrpc/client.py", line 52, in rpcexec
    response = requests.post(self.url, data=json.dumps(payload), headers=self.headers, auth=self.auth)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "delegate-feed/./main.py", line 415, in <module>
    fetch_from_wallet(rpc)
  File "delegate-feed/./main.py", line 243, in fetch_from_wallet
    rpc.info()
  File "/home/jason/.local/lib/python3.4/site-packages/bitsharesrpc/client.py", line 112, in method
    "id": 0
  File "/home/jason/.local/lib/python3.4/site-packages/bitsharesrpc/client.py", line 54, in rpcexec
    raise Exception("Connection failed! Check host, port, and authentication!")
Exception: Connection failed! Check host, port, and authentication!
[jason@sam bitshares-pytools]$ 
```

I get the same results on my servers and laptop. Have I missed something simple?

**Comment by xeroc** [comment]
It says it can't connect to the bitshares_client via RPC ..
This is how the relevant part in my bitshares config.json looks like

    "rpc": {
      "enable": true,
      "enable_cache": true,
      "rpc_user": "xeroc",
      "rpc_password": "SECRETPASSPHRASE",
      "rpc_endpoint": "127.0.0.1:9988",
      "httpd_endpoint": "127.0.0.1:19988",
      [..]
    },

and this is the content of my config.py file:

    url    = "http://127.0.0.1:19988/rpc"
    user   = 'xeroc'
    passwd = "SECRETPASSPHRASE"
    wallet = "default"
    unlock = ""

Note the port and /rpc at the end of the url .. also make sure you do not use
localhost/127.0.0.1 in the one config and your local IP (192.168.0.*) at the
other config.

**Comment by iPerky** [comment]
I am using the following config:
config.json
```
  "rpc": {
    "enable": true,
    "enable_cache": true,
    "rpc_user": "ihashfury",
    "rpc_password": "bla-bla-bla",
    "rpc_endpoint": "127.0.0.1:9988",
    "httpd_endpoint": "127.0.0.1:19988",
    "websocket_endpoint": "0.0.0.0:0",
    "encrypted_rpc_endpoint": "127.0.0.1:0",
    "encrypted_rpc_wif_key": "",
    "htdocs": "./htdocs",
    "users": []
  },
```
config.py
```
################################################################################
## RPC-client connection information (required)
################################################################################
url    = "http://127.0.0.1:19988/rpc"
user   = "ihashfury"
passwd = "bla-bla-bla"
unlock = "bla-bla-bla-bla-bla-bla"
wallet = "default"

################################################################################
## Delegate Feed Publish Parameters
################################################################################
delegate_list        = [ 
                         "delegate.ihashfury",
                         ]
#maxAgeFeedInSeconds  = 1200
maxAgeFeedInSeconds  = 1200
minValidAssetPrice   = 0.00001
discount             = 0.995
change_min           = 0.5
btc38_trust_level    = 0.7
bter_trust_level     = 1.0
poloniex_trust_level = 0.5
bittrex_trust_level  = 0.5
yunbi_trust_level    = 0.5
```

still get the error
```
$ ./main.py All
Loading data: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/usr/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jason/.local/lib/python3.4/site-packages/bitsharesrpc/client.py", line 52, in rpcexec
    response = requests.post(self.url, data=json.dumps(payload), headers=self.headers, auth=self.auth)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 415, in <module>
    fetch_from_wallet(rpc)
  File "./main.py", line 243, in fetch_from_wallet
    rpc.info()
  File "/home/jason/.local/lib/python3.4/site-packages/bitsharesrpc/client.py", line 112, in method
    "id": 0
  File "/home/jason/.local/lib/python3.4/site-packages/bitsharesrpc/client.py", line 54, in rpcexec
    raise Exception("Connection failed! Check host, port, and authentication!")
Exception: Connection failed! Check host, port, and authentication!

```

**Comment by iPerky** [comment]
This error is specific to the gui.
Using the cli on my laptop everything works as required.
Will now recheck my servers

Thanks again for the help xeroc

**Comment by xeroc** [comment]
Ah .. should have told you earlier.

The GUI uses a randomly chosen username/password ... I asked the devs for an option to get both out of the GUI somewhere so you can put them into the config. But they don't like the idea of interfacing with the GUI via RPC :(

**Comment by iPerky** [comment]
All is well in standby delegate land - bitshares-pytools feeds are working and on a cron job.
Going to setup a marketbot now :)

Excellent help
Cheers
